@SAFOnline
Feature: SAF Online scenario validations

@SAFON_IssTimeout
Scenario Outline: Validate Smartedge generates reversal due to issuer timeout


Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer receives the message but does not send the response
Then  Verify response <RejectResponse>  received by issuer as part of advice request
And   Issuer processes the reversal advice request and sends back the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>

Examples:

|TestCaseId                  |TranType                     | CardNumber           |cvv   |AcquirerResponse_F39 |AdditionalResponse_F46|RejectResponse| 
|"SAFONTimeoutPurchase"      |"Purchase"                   |"2220118912341518"    |"0206"  |   "911"            |  "2510,2701,2703,2711"     |"911"           | 
|"SAFONIssTimeoutCash"       |"Cash"                       |"2220118912341518"    |"0206"  |   "911"            |  "2510,2701,2703,2711"   |"911"           | 

@SAFON_IssLateResponse
Scenario Outline: Validate Smartedge generates reversal due to late response from issuer

Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer receives the message but does not send the response
Then  Verify response <RejectResponse>  received by issuer as part of advice request
And   Issuer processes the reversal advice request and sends back the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>
And   Issuer sends delayed response to smartedge but smartedge discards the late response

Examples:

|TestCaseId                  |TranType                 | CardNumber           |cvv  |AcquirerResponse_F39 |AdditionalResponse_F46|RejectResponse| 
|"SAFONLateRespPurchase"|"Purchase"                |"2220118912341518"    |"0206"  |   "911"            |  "2510,2701,2703,2711"   |"911"           | 
|"SAFONLateRespCash"    |"Cash"                    |"2220118912341518"    |"0206"  |   "911"            |  "2510,2701,2703,2711"   |"911"           | 



@SAFON_InconsistentResponse
Scenario Outline: Validate SmartEdge generates reversal due to issuer sending invalid response
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And  Issuer processes the message sets field <FieldName> <FieldID> <Value> and sends back the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>
Then  Verify response <IssuerResponse> and <IssuerAdditionalResponse> received by issuer as part of reversal advice request generated by SmartEdge
And   Issuer processes the reversal advice request and sends back the response


Examples:

|TestCaseId                     |TranType           | CardNumber          |cvv  |FieldName                               |FieldID   |Value                  |AcquirerResponse_F39 |AdditionalResponse_F46      |IssuerResponse   |IssuerAdditionalResponse|
|"SAFONInconstRespTC1"      |"Purchase"         |"2220118912341518"   |"0206"  | "ProcessingCode_FromAccount"           |    "3"   |   "001000"            |  "907"              |  "2701,2703,2711"               |"902"            |"2369"                  |   
|"SAFONInconstRespTC2"      |"Purchase"         |"2220118912341518"   |"0206"  | "ProcessingCode_ToAccount"             |    "3"   |   "000010"            |  "907"              |  "2701,2703,2711"               |"902"            |"2370"                  |
|"SAFONInconstRespTC3"      |"Purchase"         |"2220118912341518"   |"0206"  | "AmountTransaction"                    |    "4"   |   "289564"            |  "907"              |  "2701,2703,2711"               |"902"            |"2365"                  |
|"SAFONInconstRespTC4"      |"Purchase"         |"2220118912341518"   |"0206"  | "PrimaryAccountNumber"                 |    "2"   |   "2220118912341526"  |  "907"              |  "2701,2703,2711"               |"902"            |"2366"                  |
|"SAFONInconstRespTC5"      |"Purchase"         |"2220118912341518"   |"0206"  | "SystemsTraceAuditNumber"              |    "11"  |   "123457"            |  "907"              |  "2701,2703,2711"               |"902"            |"2371"                  |
|"SAFONInconstRespTC6"      |"Purchase"         |"2220118912341518"   |"0206"  | "MerchantCategoryCode"                 |    "26"  |   "3005"              |  "907"              |  "2701,2703,2711"               |"902"            |"2378"          |
|"SAFONInconstRespTC7"      |"Purchase"         |"2220118912341518"   |"0206"  | "CardSequenceNumber"                   |    "23"  |   "001"               |  "907"              |  "2701,2703,2711"         |"902"        |"2375"          |
|"SAFONInconstRespTC8"      |"Purchase"         |"2220118912341518"   |"0206"  | "DateAndTimeLocalTransaction"         |    "12"  |   "180320010102"      |  "907"              |  "2701,2703,2711"               |"902"            |"2372"		                |
|"SAFONInconstRespTC9"     |"Purchase"         |"2220118912341518"   |"0206"  | "AdditionalAmt"                       |    "54"   |   "1232321"               |  "907"              |  "2701,2703,2711"         |"902"        |"2397"          |
#|"SAFONInconstRespTC10"     |"Purchase"         |"2220118912341518"   |"0206"  | "Currencycodetransaction"             |    "49"   |   "360"               |  "907"              |  "2701,2703,2711"         |"902"        |"2391"          |
|"SAFONInconstRespTC11"     |"Purchase"         |"2220118912341518"   |"0206"  | "CardAcceptorNameLocation"            |    "43"   |   "TESTNAME OF MERCHANT456BOMBAYXXXXXXXKASG"               |  "907"              |  "2701,2703,2711"         |"902"        |"2389,2390,2391,2392"          |


@SAFON_IssTimeout_Repeat
Scenario Outline: Validate SmartEdge generates reversal due to timeout and then generate subsequent repeats
Given Validation of scenario <TestCaseId> for tran type "Purchase" and CardNumber "2220118912341518"
Given Initiate "Purchase" transaction for "2220118912341518" CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer receives the message but does not send the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>
And   Verify response <RejectResponse>  received by issuer as part of advice request
And   Issuer receives the platform generated repeats to platform generated reversal request and responds after <RepeatCount> repeats with expected timeout <timeout>



Examples:

|TestCaseId                  |TranType                          | CardNumber            |cvv  |AcquirerResponse_F39   |AdditionalResponse_F46   |RejectResponse   |RepeatCount       |SEID         |timeout|
| "SAFONIssTimeoutRepeat1"|"Purchase_ReversalAdvice_Request" |"2220118912341518"      |"0206"  |   "911"            |  "2510,2701,2703,2711"         |  "911"          |  "1"        |"ABCBKABL001"|"31000"|
| "SAFONIssTimeoutRepeat2"|"Purchase_ReversalAdvice_Request" |"2220118912341518"      |"0206"  |   "911"            |  "2510,2701,2703,2711"         |  "911"          |  "2"        |"ABCBKABL001"|"31000"|
| "SAFONIssTimeoutRepeat3"|"Purchase_ReversalAdvice_Request" |"2220118912341518"      |"0206"  |   "911"            |  "2510,2701,2703,2711"         |  "911"          |  "3"        |"ABCBKABL001"|"31000"|


@SAFON_Acq_reversal
Scenario Outline: Validate Acquirer generates reversal even after transaction gets approved and gets response back
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> using <Amount>
When  Acquirer forwards the message to SmartEdge
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify if acquirer received 000 response
But   Acquirer initiates "Purchase_ReversalAdvice_Request" advice request for "2220118912341518"
When  Acquirer forwards the advice request to SmartEdge after <initial_timeout> miliseconds
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>

Examples:
|TestCaseId          |TranType       | CardNumber             |Amount   |initial_timeout       |AcquirerResponse_F39   |AdditionalResponse_F46|
| "SAFONAcqReversal" |"Purchase"     |"2220118912341518"      |"11000"  |   "5000"             |"000"                  |  "2701,2703"         |


@SAFON_Acq_reversal_Before_Response
Scenario Outline: Validate Acquirer generates reversal before receiving response
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> using <Amount>
When  Acquirer forwards the message to SmartEdge
But   Acquirer initiates "Purchase_ReversalAdvice_Request" advice request for "2220118912341518"
When  Acquirer forwards the advice request to SmartEdge after <initial_timeout> miliseconds
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>

Examples:
|TestCaseId                  |TranType       | CardNumber             |Amount  |initial_timeout       |repeat_interval|AcquirerResponse_F39   |AdditionalResponse_F46|
| "SAFONAcqRevRepeat1" |"Purchase"      |"2220118912341518"      |"11000"  |   "1000"             |      "60000"      |"000"                  |  "2701,2703"         |





@SAFON_Acq_reversal_SERepeats_AcqRepeat
Scenario Outline: Validate Acquirer generates reversal even after transaction gets approved and gets response back only after first repeat from acquirer
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> using <Amount>
When  Acquirer forwards the message to SmartEdge
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify if acquirer received 000 response
But   Acquirer initiates "Purchase_ReversalAdvice_Request" advice request for "2220118912341518"
When  Acquirer forwards the advice request to SmartEdge after <initial_timeout> miliseconds
And   Issuer receives the acquirer generated reversal advice request but does not send the response
And   Issuer receives all the platform generated repeats to acquirer generated reversal request but does not respond
And   Acquirer initiates "Purchase_ReversalAdvice_Repeat" advice request after <repeat_interval>
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>


Examples:
|TestCaseId                  |TranType       | CardNumber        |Amount   |initial_timeout       |repeat_interval|AcquirerResponse_F39   |AdditionalResponse_F46|
| "SAFONAcqRevRepeat1" |"Purchase"      |"2220118912341518"      |"11000"  |   "5000"             |      "60000"      |"000"                  |  "2701,2703"         |



#@SAFON_Acq_reversal_SETimeout_AcqTimeout
Scenario Outline: Validate Acquirer generates reversal after platform has generated reversal and got a reversal advice response
Given Validation of scenario <TestCaseId> for tran type "Purchase" and CardNumber "2220118912341518"
Given Initiate "Purchase" transaction for "2220118912341518" using <Amount>
When  Acquirer forwards the message to SmartEdge 
And   Issuer receives the message but does not send the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>
And   Verify response <RejectResponse>  received by issuer as part of advice request
And   Issuer receives the platform generated repeats to platform generated reversal request and responds after <RepeatCount> repeats with expected timeout <timeout>
But   Acquirer initiates "Purchase_ReversalAdvice_Request" advice request for "2220118912341518"
When  Acquirer forwards the advice request to SmartEdge after "35000" miliseconds
Then  Verify acquirer response "000" and <AdditionalResponse_F46>

Examples:

|TestCaseId                  |TranType                | CardNumber            |Amount    |AcquirerResponse_F39   |AdditionalResponse_F46   |RejectResponse   |RepeatCount   |SEID|timeout|
| "SAFONAcqTimeout"|"Purchase_ReversalAdvice_Request" |"2220118912341518"      |"11000"  |   "911"            |  "2510,2701,2703"         |  "911"          |  "1"        |"ABCBKABL001"|"36000"|



#@SAFON_Acq_reversal_SETimeout_AcqTimeout
Scenario Outline: Validate Acquirer generates reversal after platform has generated reversal but not yet received a response
Given Validation of scenario <TestCaseId> for tran type "Purchase" and CardNumber "2220118912341518"
Given Initiate "Purchase" transaction for "2220118912341518" CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer receives the message but does not send the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>
And   Verify response <RejectResponse>  received by issuer as part of advice request
And   Issuer receives the platform generated repeats to platform generated reversal request after "21000" miliseconds
But   Acquirer initiates "Purchase_ReversalAdvice_Request" advice request for "2220118912341518"
When  Acquirer forwards the advice request to SmartEdge after "33000" miliseconds
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify acquirer response "000" and <AdditionalResponse_F46>


#Examples:

|TestCaseId                  |TranType                          | CardNumber            |cvv   |AcquirerResponse_F39   |AdditionalResponse_F46   |RejectResponse   |RepeatCount   |SEID|
| "SAFONAcqTimeoutRep"|"Purchase_ReversalAdvice_Request" |"2220118912341518"      |"0206"  |   "911"            |  "2510,2701,2703"         |  "911"          |  "1"        |"ABCBKABL001"|

@SAFON_Acq_reversal_SERepeats
Scenario Outline: Validate Acquirer generates reversal even after transaction gets approved and gets response back only after subsequent repeats from platform
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify if acquirer received 000 response
But   Acquirer initiates "Purchase_ReversalAdvice_Request" advice request for "2220118912341518"
When  Acquirer forwards the advice request to SmartEdge after <initial_timeout> miliseconds
And   Issuer receives the acquirer generated reversal advice request but does not send the response
And   Issuer receives the platform generated repeats to acquirer generated reversal request and responds after <RepeatCount> repeats with expected timeout <timeout>
And   Acquirer initiates "Purchase_ReversalAdvice_Repeat" advice request after "60000"
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>

#Examples:
|TestCaseId                  |TranType       | CardNumber             |cvv   |initial_timeout       |RepeatCount|AcquirerResponse_F39   |AdditionalResponse_F46|timeout|
| "SAFONAcqRevRepeat1" |"Purchase"      |"2220118912341518"      |"0206"  |   "5000"             |      "1"      |"000"                  |  "2701,2703,2711"         |"8000"|
#| "SAFONAcqRevRepeat2" |"Purchase"      |"2220118912341518"      |"0206"  |   "5000"             |      "2"      |"000"                  |  "2701,2703,2711"         |"31000"|
#| "SAFONAcqRevRepeat3" |"Purchase"      |"2220118912341518"      |"0206"  |   "5000"             |      "3"      |"000"                  |  "2701,2703,2711"         |"31000"|


