@PipelineFix

Feature: Transaction Consistency scenarios for Response leg
 
@TranConsistencyNonCore
Scenario Outline: Validate response message validation failed at SmartEdge for non-critical fields
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And  Issuer processes the message sets field <FieldName> <FieldID> <Value> and sends back the response
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>
Then  Verify response <IssuerResponse> and <IssuerAdditionalResponse> received by issuer as part of reversal advice request generated by SmartEdge
And   Issuer processes the reversal advice request and sends back the response


Examples:

|TestCaseId                    |TranType           | CardNumber          |cvv   |FieldName                               |FieldID   |Value                  |AcquirerResponseF39 |AdditionalResponseF46      |IssuerResponse   |IssuerAdditionalResponse|
|"TranConsNonCoreSC1TC1"      |"Purchase"         |"2220118912341518"   |"0206"| "ProcessingCodeFromAccount"           |    "3"   |   "001000"            |  "907"              |  "2701,2703,2711"               |"902"            |"2369"                  |   
|"TranConsNonCoreSC1TC2"      |"Purchase"         |"2220118912341518"    |"0206"| "ProcessingCodeToAccount"             |    "3"   |   "000010"            |  "907"              |  "2701,2703,2711"               |"902"            |"2370"                  |
|"TranConsNonCoreSC1TC3"      |"Purchase"         |"2220118912341518"   |"0206"| "AmountTransaction"                    |    "4"   |   "289564"            |  "907"              |  "2701,2703,2711"               |"902"            |"2365"                  |
|"TranConsNonCoreSC1TC4"      |"Purchase"         |"2220118912341518"   |"0206"| "PrimaryAccountNumber"                 |    "2"   |   "2220118912341526"  |  "907"              |  "2701,2703,2711"               |"902"            |"2366"                  |
|"TranConsNonCoreSC1TC5"      |"Purchase"         |"2220118912341518"   |"0206"| "SystemsTraceAuditNumber"              |    "11"  |   "123457"            |  "907"              |  "2701,2703,2711"               |"902"            |"2371"                  |
|"TranConsNonCoreSC1TC6"      |"Purchase"         |"2220118912341518"   |"0206"| "MerchantCategoryCode"                 |    "26"  |   "3005"              |  "907"              |  "2701,2703,2711"               |"902"            |"2378"          |
|"TranConsNonCoreSC1TC7"      |"Purchase"         |"2220118912341518"   |"0206"| "CardSequenceNumber"                   |    "23"  |   "001"               |  "907"              |  "2701,2703,2711"               |"902"            |"2375"          |
|"TranConsNonCoreSC1TC8"      |"Purchase"         |"2220118912341518"    |"0206"| "DateAndTimeLocalTransaction"         |    "12"  |   "180320010102"      |  "907"              |  "2701,2703,2711"               |"902"            |"2372"		                |
|"TranConsNonCoreSC1TC9"     |"Purchase"         |"2220118912341518"   |"0206"| "AdditionalAmt"                         |    "54"   |   "1232321"          |  "907"              |  "2701,2703,2711"               |"902"            |"2397"          |
|"TranConsNonCoreSC1TC10"     |"Purchase"         |"2220118912341518"   |"0206"| "Currencycodetransaction"             |    "49"   |   "356"               |  "907"              |  "2701,2703,2711"               |"902"            |"2394"          |
|"TranConsNonCoreSC1TC11"     |"Purchase"         |"2220118912341518"   |"0206"| "CardAcceptorNameLocation"            |    "43"   |   "TESTNAME OF MERCHANT456BOMBAYXXXXXXXKASG"               |  "907"              |  "2701,2703,2711"         |"902"        |"2389,2390,2391,2392"          |
#|"TranConsNonCoreSC1TC16"     |"Purchase"         |"2220118912341518"   |"0206"| "ForwardInstitutioncode"                   |    "33"  |   "900008"               |  "907"              |  "2701,2703,2711"         |"902"        |"2381"          |



# Soft Reject - NonCore Feild !!!!!!!!!!!!!


@TranConsistencyNonCoreFieldSoftReject
Scenario Outline: Validate response message validation failed at SmartEdge for non-critical fields
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer processes the message sets field <FieldName> <FieldID> <Value> and sends back the response
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>

Examples:

|TestCaseId        |TranType           | CardNumber              |cvv   |FieldName                               |FieldID   |Value                  |AcquirerResponseF39 |AdditionalResponseF46  |    
|"TranConsPOSTC1"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeInputCapability"           |    "22"  |   "010101510300"      |  "000"              |  "2353"              |              
|"TranConsPOSTC2"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationCapability"  |    "22"  |   "500101510300"      |  "000"              |  "2354"             |
|"TranConsPOSTC3"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCaptureCapability"         |    "22"  |   "511101510300"      |  "000"              |  "2355"             |
|"TranConsPOSTC4"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeOperatingEnvironment"      |    "22"  |   "510001510300"      |  "000"              |  "2356"              |
|"TranConsPOSTC5"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardholderPresent"         |    "22"  |   "510111510300"      |  "000"              |  "2357"              |
|"TranConsPOSTC6"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardPresent"               |    "22"  |   "510100510300"      |  "000"              |  "2358"              |
|"TranConsPOSTC7"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardDataInputMode"         |    "22"  |   "510101010300"      |  "000"              |  "2359"              |
|"TranConsPOSTC8"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationMethod"      |    "22"  |   "510101500300"      |  "000"              |  "2360"              |
|"TranConsPOSTC9"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationEntity"      |    "22"  |   "510101511300"      |  "000"              |  "2361"              |
|"TranConsPOSTC10"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeOutputCapability"          |    "22"  |   "510101510000"      |  "000"              |  "2362"             |
|"TranConsPOSTC11"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeTerminalCapability"        |    "22"  |   "510101510310"      |  "000"              |  "2363"             |
|"TranConsPOSTC12"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodePINCaptureCapability"      |    "22"  |   "510101510301"      |  "000"              |  "2364"             |
    

   #@TLCInavlidResponseCoreFieldReversal
 #Bug id 161  
Scenario Outline: Validate response message validation failed at SmartEdge for critical fields for Reversal

Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify if acquirer received 000 response
But   Acquirer initiates "PurchaseReversalAdviceRequest" advice request for <CardNumber> 
When  Acquirer forwards the message to SmartEdge
And   Issuer processes the reversal advice request and sets field <FieldName> <FieldID> <Value> and sends back the response to acquirer
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>
And   Verify reject response <RejectResponseF39> received by issuer as part of reversal advice generated by SmartEdge due to consistency check mismatch 
And   Issuer processes the message and sends back the response
   
    #Examples:  
    |TestCaseId                     |TranType         | CardNumber        |cvv    |FieldName                             |FieldID    |Value                 |AcquirerResponseF39  |AdditionalResponseF46 |IssuerResponse|IssuerAdditionalResponse|
    |"TCChkSC1TC1MTI"               |"Purchase"       |"2220118912341518" |"0206" | "MTI"                                |  "0"      |   "1300"             |  "911"              |  "2510,2701,2703"    |      "902"   |"2378"                  |
    #|"TCChkSC1TC2FUNCD"            |"Purchase"       |"2220118912341518" |"0206"| "FunctionCode"                       |   "24"   |   "205"               |  "911"              |  "2510,2701,2703"     |  "902"       |"2376"                  |
    #|"TCChkSC1TC3PRCCDTNTYP        |"Purchase"       |"2220118912341518" |"0206"| "ProcessingCodeTranType"            |    "3"   |   "010000"            |  "911"              |  "2510,2701,2703"     |"902"         |"2368"                  |
    #|"TCChkSC1TC4ACQINSTCD"        |"Purchase"       |"2220118912341518" |"0206"| "AcquiringInstitutionIdCode"         |    "32"  |   "999992"            |  "911"              |  "2510,2701,2703"     |"902"         |"2380"                  |
    #|"TCChkSC1TC5RRN"              |"Purchase"       |"2220118912341518" |"0206"| "RetrievalReferenceNumber"           |   "37"   |   "123456712345"      |  "911"              |  "2510,2701,2703"     |"902"         |"2384"                  |
    #|"TCChkSC1TC6CRDACCPTTRMID"   |"Purchase"       |"2220118912341518" |"0206"| "CardAcceptorTerminalId"             |    "41"  |   "12345667"          |  "911               |  "2510,2701,2703"     |"902"         |"2387"                  |
    #|"TCChkSC1TC7CRDACCPTCD"       |"Purchase"       |"2220118912341518" |"0206"| "CardAcceptorIdCode"                 |    "42"  |   "123456781234565"   |  "911"              |  "2510,2701,2703"     |"902"         |"2388"                  |
 #
  
  #
#@TLCInavlidResponseNonCoreFieldforReversal
 #Bug id 161     
Scenario Outline: Validate response message validation failed at SmartEdge for non-critical fields for reversal generated by SE
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify if acquirer received 000 response
But   Acquirer initiates "PurchaseReversalAdviceRequest" advice request for <CardNumber> 
When  Acquirer forwards the message to SmartEdge
And   Issuer processes the reversal advice request and sets field <FieldName> <FieldID> <Value> and sends back the response to acquirer
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>
And   Verify reject response <RejectResponseF39> received by issuer as part of reversal advice generated by SmartEdge due to consistency check mismatch 
And   Issuer processes the message and sends back the response

 #Examples:

|TestCaseId        |TranType           | CardNumber          |cvv |FieldName                               |FieldID   |Value                  |AcquirerResponseF39 |AdditionalResponseF46      |RejectResponseF39  | 
|"TLC1SC3TC1"      |"Purchase"         |"2220118912341518"   |"0206"| "ProcessingCodeFromAccount"           |    "3"   |   "001000"            |  "907"              |  "2701,2703"               |"902"            |
#|"TLC1SC3TC2"      |"Purchase"         |"2220118912341518"   |"0206"| "ProcessingCodeToAccount"             |    "3"   |   "000010"            |  "907"              |  "2701,2703"               |"902"            |"2370"                  |
#|"TLC1SC3TC3"      |"Purchase"         |"2220118912341518"   |"0206"| "AmountTransaction"                    |    "4"   |   "289564"            |  "907"              |  "2701,2703"               |"902"            |"2365"                  |
#|"TLC1SC3TC4"      |"Purchase"         |"2220118912341518"   |"0206"| "PrimaryAccountNumber"                 |    "2"   |   "2220118912341526"  |  "907"              |  "2701,2703"               |"902"            |"2366"                  |
#|"TLC1SC3TC5"      |"Purchase"         |"2220118912341518"   |"0206"| "SystemsTraceAuditNumber"              |    "11"  |   "123457"            |  "907"              |  "2701,2703"               |"902"            |"2357"                  |
#|"TLC1SC3TC6       |"Purchase"         |"2220118912341518"   |"0206"| "DateAndTimeLocalTransaction"          |    "12"  |   "180320010102"      |  "907"              |  "2701,2703"               |"902"            |"2372		                |
#|"TLC1SC3TC7"      |"Purchase"         |"2220118912341518"   |"0206"| "MerchantCategoryCode"                 |    "26"  |   "3005"              |  "907"              |  "2701,2703"               |"902"            |"2378"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "CardSequenceNumber"                   |    "23"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2375"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "Date Expiration"                      |    "14"  |   "1911"               |  "907"              |  "2701,2703"         |"902"        |"2373"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "AdditionalAmt"                       |    "54"   |   "12323211"               |  "907"              |  "2701,2703"         |"902"        |"2394"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "Currencycodetransaction"             |    "42"   |   "365"               |  "907"              |  "2701,2703"         |"902"        |"2391"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "CardAcceptorNameLocation"            |    "43"   |   "111"               |  "907"              |  "2701,2703"         |"902"        |"2389"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "ResponseCode"                        |    "39"   |   "905"               |  "907"              |  "2701,2703"         |"902"        |"2371"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "DateSettlement"                      |    "23"   |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2374"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "SecurityRelatedControlInformation"                   |    "53"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2394"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "ForwardInstitutioncode"                   |    "33"  |   "111"               |  "907"              |  "2701,2703"         |"902"        |"2381"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "ServiceRestrictioncode"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalAmount"                        |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalDataElements"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "CCYCDOriginal"                           |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalAcquiringInstitutionIdCode"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalCardAcceptorTerminalId"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalCardAcceptorIdCode"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalFunctionCode"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "OriginalRetrievalReferenceNumber"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "ServiceRestrictioncode"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |
#|"TLC1SC3TC20"     |"Purchase"         |"2220118912341518"   |"0206"| "ServiceRestrictioncode"                   |    "40"  |   "001"               |  "907"              |  "2701,2703"         |"902"        |"2386"          |




#@TLCInavlidResponseNonCoreFieldforReversalforsoftreject
 
Scenario Outline: Validate response message validation failed at SmartEdge for non-critical fields for reversal generated by SE
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Message is processed by issuer and repsonse is sent back to the acquirer
Then  Verify if acquirer received 000 response
But   Acquirer initiates "PurchaseReversalAdviceRequest" advice request for <CardNumber> 
When  Acquirer forwards the message to SmartEdge
And   Issuer processes the reversal advice request and sets field <FieldName> <FieldID> <Value> and sends back the response to acquirer
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>
And   Verify reject response <RejectResponseF39> received by issuer as part of reversal advice generated by SmartEdge due to consistency check mismatch 
And   Issuer processes the message and sends back the response

#
#Examples:

|TestCaseId        |TranType           | CardNumber          |cvv   |FieldName                               |FieldID   |Value                  |AcquirerResponseF39 |AdditionalResponseF46  |    
|"TLC1SC3TC7"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeInputCapability"           |    "22"  |   "11030X112345"      |  "000"              |  "2353"      |              
#|"TLC1SC3TC8"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationCapability"  |    "22"  |   "00030X112345"      |  "000"              |  "2354"                    |
#|"TLC1SC3TC9"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCaptureCapability"         |    "22"  |   "01330X112345"      |  "000"              |  "2355"                    |
#|"TLC1SC3TC10"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeOperatingEnvironment"      |    "22"  |   "01040X112345"      |  "000"              |  "2356"                    |
#|"TLC1SC3TC11"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardholderPresent"         |    "22"  |   "01035X112345"      |  "000"              |  "2357"                    |
#|"TLC1SC3TC12"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardPresent"               |    "22"  |   "010303112345"      |  "000"              |  "2358"                    |
#|"TLC1SC3TC13"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardDataInputMode"         |    "22"  |   "01030X012345"      |  "000"              |  "2359"                    |
#|"TLC1SC3TC14"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationMethod"      |    "22"  |   "01030X102345"      |  "000"              |  "2360"                    |
#|"TLC1SC3TC15"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationEntity"      |    "22"  |   "01030X111345"      |  "000"              |  "2361"                    |
#|"TLC1SC3TC16"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeOutputCapability"          |    "22"  |   "01030X112245"      |  "000"              |  "2362"                    |
#|"TLC1SC3TC17"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeTerminalCapability"        |    "22"  |   "01030X112315"      |  "000"              |  "2363"                    |
#|"TLC1SC3TC18"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodePINCaptureCapability"      |    "22"  |   "01030X112343"      |  "000"              |  "2364"                    |
   #
