@PipelineFix
Feature: Transaction LifeCyle scenarios for failure in response leg
#@TLC_IssuerUnavailable
@IssuerUnavailable
Scenario: Validate request leg failed while forwarding to issuer
Given Validation of scenario "TLC1SC1TC1" for tran type "Purchase" and CardNumber "2220118912341518"
Given Initiate "Purchase" transaction for "2220118912341518" CVV as "0206"
When  Acquirer forwards the message to SmartEdge 
Then  Verify acquirer response "911" and "2510,2701,2703,2711"

#@TLC_InavlidResponse_CoreField
Scenario Outline: Validate response message validation failed at SmartEdge for critical fields
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer processes the message sets field <FieldName> <FieldID> <Value> and sends back the response
Then   Verify response <IssuerResponse> and <IssuerAdditionalResponse> received by issuer as part of reversal advice request generated by SmartEdge
And   Verify response "911"  received by issuer as part of advice request
And  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>
And   Issuer processes the message and sends back the response
#Blocked due to issue 763

#Examples:
|TestCaseId   |TranType          | CardNumber        |cvv  |FieldName                              |FieldID   |Value                 |AcquirerResponse_F39 |AdditionalResponse_F46 |IssuerResponse|IssuerAdditionalResponse|
#|"TLC1SC2TC1"|"Purchase"       |"2220118912341518" |"0206"|"MTI"                                |  "0"     |    "1300"             | "911"               |  "2510,2701,2703"     |      "911"               |  "2701,2703"  |
#|"TLC1SC2TC2"|"Purchase"       |"2220118912341518" |"0206"| "FunctionCode"                       |   "24"   |   "201"               |  "911"              |  "2510,2701,2703"     |  "914"         |"2101"          |
|"TLC1SC2TC3"|"Purchase"       |"2220118912341518" |"0206"| "ProcessingCode_TranType"            |    "3"   |   "010000"            |  "911"              |  "2510,2701,2703,2711"     |"914"        |"2101"          |
#|"TLC1SC2TC4"|"Purchase"       |"2220118912341518" |"0206"| "AcquiringInstitutionIdCode"         |    "32"  |   "900002"            |  "911"              |  "2510,2701,2703,2711"     |"902"         |"2380"          |
#|"TLC1SC2TC5"|"Purchase"       |"2220118912341518" |"0206"| "RetrievalReferenceNumber"           |   "37"  |   "123456712345"    |  "911"              |  "2510,2701,2703,2711"     |"902"         |"2384"          |
#|"TLC1SC2TC6"|"Purchase"       |"2220118912341518" |"0206"| "CardAcceptorTerminalId"             |    "41"  |   "12345667"          |  "911"              |  "2510,2701,2703,2711"     |"902"         |"2387"          |
#|"TLC1SC2TC7"|"Purchase"       |"2220118912341518" |"0206"| "CardAcceptorIdCode"                 |    "42"  |   "123456781234565"   |  "911"              |  "2510,2701,2703,2711"     |"902"         |"2388"          |



@TLC_InavlidResponse_NonCoreField
Scenario Outline: Validate response message validation failed at SmartEdge for non-critical fields
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And  Issuer processes the message sets field <FieldName> <FieldID> <Value> and sends back the response
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>
Then  Verify response <IssuerResponse> and <IssuerAdditionalResponse> received by issuer as part of reversal advice request generated by SmartEdge
And   Issuer processes the reversal advice request and sends back the response


Examples:

|TestCaseId                     |TranType           | CardNumber    |cvv    |FieldName                               |FieldID   |Value                  |AcquirerResponseF39 |AdditionalResponseF46      |IssuerResponse   |IssuerAdditionalResponse|
|"InvalidrespSC1TC1"      |"Purchase"         |"2220118912341518"   |"0206"| "ProcessingCodeFromAccount"           |    "3"   |   "001000"            |  "907"              |  "2701,2703,2711"               |"902"            |"2369"                  |   
|"InvalidRespSC1TC2"      |"Purchase"         |"2220118912341518"   |"0206"| "ProcessingCodeToAccount"             |    "3"   |   "000010"            |  "907"              |  "2701,2703,2711"               |"902"            |"2370"                  |
|"InvalidRespSC1TC3"      |"Purchase"         |"2220118912341518"   |"0206"| "AmountTransaction"                    |    "4"   |   "289564"            |  "907"              |  "2701,2703,2711"               |"902"            |"2365"                  |
|"InvalidRespSC1TC4"      |"Purchase"         |"2220118912341518"   |"0206"| "PrimaryAccountNumber"                 |    "2"   |   "2220118912341526"  |  "907"              |  "2701,2703,2711"               |"902"            |"2366"                  |
|"InvalidRespSC1TC5"      |"Purchase"         |"2220118912341518"   |"0206"| "SystemsTraceAuditNumber"              |    "11"  |   "123457"            |  "907"              |  "2701,2703,2711"               |"902"            |"2371"                  |
|"InvalidRespSC1TC6"      |"Purchase"         |"2220118912341518"   |"0206"| "MerchantCategoryCode"                 |    "26"  |   "3005"              |  "907"              |  "2701,2703,2711"               |"902"            |"2378"          |
|"InvalidRespSC1TC7"      |"Purchase"         |"2220118912341518"   |"0206"| "CardSequenceNumber"                   |    "23"  |   "001"               |  "907"              |  "2701,2703,2711"         |"902"        |"2375"          |
|"InvalidRespSC1TC8"      |"Purchase"         |"2220118912341518"    | "0206"|"DateAndTimeLocalTransaction"         |    "12"  |   "180320010102"      |  "907"              |  "2701,2703,2711"               |"902"            |"2372"		                |
|"InvalidRespSC1TC9"     |"Purchase"         |"2220118912341518"   |"0206"| "AdditionalAmt"                       |    "54"   |   "1232321"               |  "907"              |  "2701,2703,2711"         |"902"        |"2397"          |
|"InvalidRespSC1TC10"     |"Purchase"         |"2220118912341518"   |"0206"| "Currencycodetransaction"             |    "49"   |   "356"               |  "907"              |  "2701,2703,2711"         |"902"        |"2394"          |
|"InvalidRespSC1TC11"     |"Purchase"         |"2220118912341518"   |"0206"| "CardAcceptorNameLocation"            |    "43"   |   "TESTNAME OF MERCHANT456BOMBAYXXXXXXXKASG"               |  "907"              |  "2701,2703,2711"         |"902"        |"2389,2390,2391,2392"          |
#Need to change profile|"InvalidRespSC1TC16"     |"Purchase"         |"2220118912341518"   |"0206"| "ForwardInstitutioncode"                   |    "33"  |   "900008"               |  "907"              |  "2701,2703"         |"902"        |"2381"          |




# Soft Reject - NonCore Field

@InvalidRespistencyNonCoreFieldSoftReject
Scenario Outline: Validate response message validation failed at SmartEdge for non-critical fields
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer processes the message sets field <FieldName> <FieldID> <Value> and sends back the response
Then  Verify acquirer response <AcquirerResponseF39> and <AdditionalResponseF46>

Examples:

|TestCaseId               |TranType           | CardNumber          |cvv   |FieldName                               |FieldID   |Value                  |AcquirerResponseF39 |AdditionalResponseF46  |    
|"InvalidRespPOSTC1"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeInputCapability"           |    "22"  |   "110101510300"      |  "000"              |  "2353"      |              
|"InvalidRespPOSTC2"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationCapability"  |    "22"  |   "500101510300"      |  "000"              |  "2354"                    |
|"InvalidRespPOSTC3"      |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCaptureCapability"         |    "22"  |   "511101510300"      |  "000"              |  "2355"                    |
|"InvalidRespPOSTC4"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeOperatingEnvironment"      |    "22"  |    "510001510300"      |  "000"              |  "2356"                    |
|"InvalidRespPOSTC5"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardholderPresent"         |    "22"  |    "510111510300"      |  "000"              |  "2357"                    |
|"InvalidRespPOSTC6"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardPresent"               |    "22"  |    "510100510300"      |  "000"              |  "2358"                    |
|"InvalidRespPOSTC7"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeCardDataInputMode"         |    "22"  |    "510101110300"      |  "000"              |  "2359"                    |
|"InvalidRespPOSTC8"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationMethod"      |    "22"  |    "510101500300"      |  "000"              |  "2360"                    |
|"InvalidRespPOSTC9"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeAuthenticationEntity"      |    "22"  |    "510101511300"      |  "000"              |  "2361"                    |
|"InvalidRespPOSTC10"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeOutputCapability"          |    "22"  |   "510101510100"      |  "000"              |  "2362"                    |
|"InvalidRespPOSTC11"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodeTerminalCapability"        |    "22"  |   "510101510310"      |  "000"              |  "2363"                    |
|"InvalidRespPOSTC12"     |"Purchase"         |"2220118912341518"   |"0206"| "PosDataCodePINCaptureCapability"      |    "22"  |   "510101510301"      |  "000"              |  "2364"                    |
      


@TLC_ISS_TIMEOUT_LateResponse
Scenario Outline: Validate response leg failed from issuer to smartedge
Given Validation of scenario <TestCaseId> for tran type <TranType> and CardNumber <CardNumber>
Given Initiate <TranType> transaction for <CardNumber> CVV as <cvv>
When  Acquirer forwards the message to SmartEdge 
And   Issuer Validates <scenario> ,processes the message and sends back the response
Then  Verify acquirer response <AcquirerResponse_F39> and <AdditionalResponse_F46>

Examples:

|TestCaseId |TranType          | CardNumber        |cvv   |scenario                               |AcquirerResponse_F39 |AdditionalResponse_F46|IssuerResponse|IssuerAdditionalResponse|
|"TLC1SC4TC1"|"Purchase"        |"2220118912341518" |"0206"| "Issuer_Timeout"                      |      "911"            |  "2510,2701,2703,2711"   |"907"       | "2701,2703"  |
|"TLC1SC4TC2"|"Purchase"        |"2220118912341518" |"0206"| "Issuer_LateResponse"                 |      "911"            |  "2510,2701,2703,2711"   |"907"       | "2701,2703"  |


