import os
import getpass
profile_path = {
   'se_services_profile':['account_range.profile',
                           'acquirer.profile',
                           'brand.profile',
                           'card_product.profile',
                           'card_product_scheme.profile',
                           'end_point.profile',
                           'formatter.profile',
                           'header_formats.profile',
                           'network.profile',
                           'processor.profile',
                           'route.profile',
                           'se_entity.profile',
                           'tran_type_to_field_mapping.profile'
                           ],

    'se_services_platform':['card_product_id_to_limit_mapping.profile',
                            'accumulation_group_rules.profile',
                            'action_code_to_task_list.profile',
                            'advice_notification_config.profile',
                            'amount_tier_configuration.profile',
                            'attributes_timeout.profile',
                            'card_number_reject_code_mapping.profile',
                            'country_code.profile',
                            'currency_code.profile',
                            'dashboard_metrics_label_mapping.profile',
                            'data_field_definition.profile',
                            'destination_end_point.profile',
                            'dr_cr_rule.profile',
                            'end_point.CT.profile',
                            'event_code_to_action_code.profile',
                            'extended_tran_type_parameters.profile',
                            'fee_groups.profile',
                            'fee_rates.profile',
                            'fee_rules.profile',
                            'formatter_1_response_code.profile',
                            'formatter_se_response_code_mapping.profile',
                            'function_code.profile',
                            'header_field_definition.profile',
                            'ledger_template.profile',
                            'mcc_for_network_id_1.profile',
                            'mcc_for_network_id_2.profile',
                            'merchant_category_code.profile',
                            'message_reason_code.profile',
                            'message_type_identifier.profile',
                            'parent_se_context_update_dummy',
                            'pin_block.profile',
                            'pos_data_code_PIN_capture_capability.profile',
                            'pos_data_code_authentication_capability.profile',
                            'pos_data_code_authentication_entity.profile',
                            'pos_data_code_authentication_method.profile',
                            'pos_data_code_capture_capability.profile',
                            'pos_data_code_card_data_input_mode.profile',
                            'pos_data_code_card_holder_present.profile',
                            'pos_data_code_card_present.profile',
                            'pos_data_code_input_capability.profile',
                            'pos_data_code_operating_environment.profile',
                            'pos_data_code_output_capability.profile',
                            'pos_data_code_terminal_capability.profile',
                            'processing_code_transaction_type.profile',
                            'recovery_advice_notification_config.profile',
                            'recovery_mode_config.profile',
                            'recovery_mode_priority.profile',
                            'route_rules.profile',
                            'se_context_log.profile',
                            'se_end_point_attributes_score.profile',
                            'se_reject_code.profile',
                            'se_response_code.profile',
                            'service_restriction_code_pos_1.profile',
                            'service_restriction_code_pos_2.profile',
                            'service_restriction_code_pos_3.profile',
                            'stip_applicability_conditional_rule.profile',
                            'stip_config_task_list.profile',
                            'task_list.profile',
                            'task_list_configuration.profile',
                            'to_or_from_account.profile',
                            'tran_type_key.profile',
                            'tran_type_parameters.profile',
                            'tran_type_to_fee_groups.profile',
                            'tran_type_to_key_fields.profile',
                            'tran_type_to_ledger_direction_mapping.profile',
                            'transaction_consistency_check_config.profile',
                            'transaction_source.profile',
                            'transaction_type.profile',
                            'txn_rules_map.profile',
                            'tran_type_to_dr_cr.profile',
                            'diversion_threshold_table.profile',
                            'sdcm_reset_time.profile',
                            'sdcm_tran_type.profile',
                            'issuer_defined_limits.profile',
                            'se_defined_limits.profile',
                            'se_defined_activity_limits.profile',
                            'issuer_defined_activity_limits.profile',
                            'file_update_action.profile',
                            'file_update_name.profile',
                            'file_data_definitions.profile',
                            'file_update_message_validation_data.profile',
                            'time_out_config.profile',
                            'se_activity_group.profile',
                            'issuer_defined_exception_code.profile',
                            'activity_limit_config.profile'
                        ],

    'endpoint_handler_profile':['end_point.profile'],

    'endpoint_handler_platform':['dashboard_metrics_label_mapping.profile'],

    'message_processor_profile':['header_formats.profile',
                                 'formatter.profile',
                                 'network.profile',
                                 'tran_type_to_field_mapping.profile',
                                 'end_point.profile'],

    'message_processor_platform':['destination_end_point.profile',
                                  'mti_to_landing_service_mapping.profile',
                                  'se_context_log.profile',
                                  'mti_to_state.profile',
                                  'se_reject_code.profile'],

    'se_recovery_manager_profile':['se_entity.profile'],

    'se_recovery_manager_platform':['recovery_mode.profile'],

    'event_fees_consumer_profile':[],

    'event_fees_consumer_platform':  ['event_id_to_event_fee_groups.profile',
				      'dr_cr_rule.profile',
				      'fee_groups.profile',
				      'fee_rates.profile',
				      'fee_rules.profile'],

    'se_accumulator_profile':['se_entity.profile',
                              'network.profile'],

    'se_accumulator_platform':['acc_group_fee_rate.profile'],

    'accumulator_fees_calculator_profile':['se_entity.profile',
                                           'network.profile'],

    'accumulator_fees_calculator_platform':['acc_group_fee_rate.profile',
                                            'dr_cr_rule.profile',
                                            'fee_rates.profile',
                                            'acc_group_id.profile'],

    'settlement_date_mgr_profile':['se_entity.profile',
                                   'network.profile'],

    'settlement_date_mgr_platform':['acc_group_fee_rate.profile',
                                    'dr_cr_rule.profile',
                                    'fee_rates.profile',
                                    'acc_group_id.profile'],

    'clearing_date_and_cycle_creation_profile':[],

    'clearing_date_and_cycle_creation_platform':['clearing_cycles_info.profile',
                                                 'clearing_holiday_list.profile',
                                                 'settlement_holiday_list.profile'],

    'activity_limit_setter_profile':['se_entity.profile',
                                     'network.profile',
                                     'card_product.profile',
                                     'account_range.profile'],

    'activity_limit_setter_platform':['country_code.profile',
                                      'merchant_category_code.profile']
}

home_dir = os.path.join('/home/', getpass.getuser())
